const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
// Local convenience only: values in .env remain outside the source code and archive.
const envFile=path.join(__dirname,'.env');
if(fs.existsSync(envFile))fs.readFileSync(envFile,'utf8').split(/\r?\n/).forEach(line=>{const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')});

const PORT = process.env.PORT || 3000;
const DB = path.join(__dirname, 'data.json');
const sessions = new Map();
const streams = new Set();
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const money = n => Math.round(Number(n) * 100) / 100;
const cic = {tpe:process.env.CIC_TPE,company:process.env.CIC_SOCIETE,key:process.env.CIC_KEY,baseUrl:process.env.PUBLIC_BASE_URL,mode:process.env.CIC_MODE||'test'};
const stripe = {secret:process.env.STRIPE_SECRET_KEY,webhook:process.env.STRIPE_WEBHOOK_SECRET,configuration:process.env.STRIPE_PAYMENT_METHOD_CONFIGURATION,baseUrl:process.env.PUBLIC_BASE_URL};
const printAgentToken = process.env.PRINT_AGENT_TOKEN || '';
const cicReady = () => !!(cic.tpe && cic.company && /^[0-9a-f]{40}$/i.test(cic.key||'') && /^https:\/\//.test(cic.baseUrl||''));
const stripeReady = () => !!(stripe.secret && stripe.webhook && /^https?:\/\//.test(stripe.baseUrl||''));
function formBody(req){return new Promise(resolve=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>resolve(Object.fromEntries(new URLSearchParams(raw))));});}
function rawBody(req){return new Promise(resolve=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>resolve(raw));});}
function cicMac(fields){const content=Object.keys(fields).filter(k=>k!=='MAC').sort().map(k=>`${k}=${fields[k]??''}`).join('*');return crypto.createHmac('sha1',Buffer.from(cic.key,'hex')).update(content,'utf8').digest('hex');}
function cicFields(order){const date=new Date(),stamp=[String(date.getDate()).padStart(2,'0'),String(date.getMonth()+1).padStart(2,'0'),date.getFullYear()].join('/')+':'+[date.getHours(),date.getMinutes(),date.getSeconds()].map(n=>String(n).padStart(2,'0')).join(':');const reference=`MBWP${order.number}`;const context=Buffer.from(JSON.stringify({orderId:order.id,reference,items:order.items.map(i=>({name:i.name,quantity:i.qty,unitPrice:i.priceHt}))}),'utf8').toString('base64');const fields={TPE:cic.tpe,contexte_commande:context,date:stamp,lgue:'FR',montant:`${order.total.ttc.toFixed(2)}EUR`,reference,societe:cic.company,'texte-libre':order.id,version:'3.0',url_retour_err:`${cic.baseUrl}/api/payments/cic/return?order=${encodeURIComponent(order.id)}&result=error`,url_retour_ok:`${cic.baseUrl}/api/payments/cic/return?order=${encodeURIComponent(order.id)}&result=success`};return {...fields,MAC:cicMac(fields)};}
function printAgent(req){return !!printAgentToken&&req.headers['x-print-agent-token']===printAgentToken;}
function stripePost(path,params){return new Promise((resolve,reject)=>{const body=new URLSearchParams(params).toString(),r=require('https').request({hostname:'api.stripe.com',path,method:'POST',headers:{Authorization:'Basic '+Buffer.from(`${stripe.secret}:`).toString('base64'),'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(body)}},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{const parsed=JSON.parse(out);res.statusCode>=200&&res.statusCode<300?resolve(parsed):reject(Error(parsed.error?.message||'Erreur Stripe'))}catch{reject(Error('Réponse Stripe invalide'))}})});r.on('error',reject);r.end(body)})}
function verifyStripe(req,raw){const signature=String(req.headers['stripe-signature']||''),timestamp=signature.match(/(?:^|,)t=(\d+)/)?.[1],received=signature.match(/(?:^|,)v1=([a-f0-9]+)/i)?.[1];if(!timestamp||!received||Math.abs(Date.now()/1000-Number(timestamp))>300)return false;const expected=crypto.createHmac('sha256',stripe.webhook).update(`${timestamp}.${raw}`,'utf8').digest('hex');return received.length===expected.length&&crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected));}

function seed() {
  return { venue:{name:'Madiana Bowling by West Paradise',currency:'EUR',taxIncluded:true},
    users:[{id:'u1',name:'Administrateur',email:'admin@mbwp.demo',password:'Demo2026!',role:'ADMIN'},{id:'u2',name:'Bar / Cuisine',email:'bar@mbwp.demo',password:'Demo2026!',role:'KITCHEN'},{id:'u3',name:'Manager',email:'manager@mbwp.demo',password:'Demo2026!',role:'MANAGER'}],
    categories:[
      {id:'c1',name:'Boissons',icon:'🥤',sort:1,active:true,parentId:null},{id:'c2',name:'Salé & Sucré',icon:'🍔',sort:2,active:true,parentId:null},
      {id:'c3',name:'Cocktails avec alcool',icon:'🍹',sort:1,active:true,parentId:'c1'},{id:'c4',name:'Softs',icon:'🥤',sort:2,active:true,parentId:'c1'},
      {id:'c5',name:'Burgers',icon:'🍔',sort:1,active:true,parentId:'c2'},{id:'c6',name:'Snacks',icon:'🍟',sort:2,active:true,parentId:'c2'}],
    products:[
      {id:'p1',sku:'BUR-CHEESE',name:'Cheeseburger',description:'Steak grillé, cheddar, salade et sauce maison.',categoryId:'c5',priceHt:15,taxRate:20,cost:6.2,stock:42,active:true,featured:true,image:''},
      {id:'p2',sku:'BUR-BACON',name:'Burger Bacon',description:'Steak grillé, bacon croustillant, cheddar et sauce barbecue.',categoryId:'c5',priceHt:16.67,taxRate:20,cost:7.4,stock:28,active:true,featured:true,image:''},
      {id:'p3',sku:'DRK-COCA',name:'Coca-Cola 33 cl',description:'Boisson fraîche servie en bouteille.',categoryId:'c4',priceHt:2.92,taxRate:20,cost:0.65,stock:96,active:true,featured:false,image:''},
      {id:'p4',sku:'DRK-HEIN',name:'Bière locale',description:'Bière fraîche locale, 33 cl.',categoryId:'c4',priceHt:5.83,taxRate:20,cost:1.6,stock:47,active:true,featured:false,image:''},
      {id:'p5',sku:'SNK-FRITES',name:'Frites maison',description:'Pommes de terre fraîches, sauce au choix.',categoryId:'c6',priceHt:4.17,taxRate:20,cost:1.1,stock:55,active:true,featured:false,image:''},
      {id:'p6',sku:'SNK-NACHOS',name:'Nachos fromage',description:'Chips de maïs, fromage fondu et salsa.',categoryId:'c6',priceHt:7.5,taxRate:20,cost:2.85,stock:31,active:true,featured:true,image:''},
      {id:'p7',sku:'CKT-MOJITO',name:'Mojito',description:'Rhum blanc, sucre de canne, citron vert, menthe fraîche et eau gazeuse.',categoryId:'c3',priceHt:8.33,taxRate:20,cost:2.5,stock:38,active:true,featured:true,image:''}],
    lanes:Array.from({length:8},(_,i)=>({id:`l${i+1}`,number:i+1,token:crypto.randomBytes(12).toString('hex'),active:true})),orders:[],audit:[] };
}
function load(){ if(!fs.existsSync(DB)){const d=seed(); fs.writeFileSync(DB,JSON.stringify(d,null,2)); return d} return JSON.parse(fs.readFileSync(DB,'utf8')); }
let db=load();
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2));}
function audit(user,action,detail){ db.audit.unshift({id:id(),at:now(),user:user?.name||'Client',action,detail}); db.audit=db.audit.slice(0,200); }
function event(type,payload){ for(const r of streams) r.write(`event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`); }
function releaseStock(order){if(order.stockReleased)return;order.items.forEach(i=>{const p=db.products.find(x=>x.id===i.productId);if(p)p.stock+=i.qty});order.stockReleased=true;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function parse(req){return new Promise((ok,bad)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{ok(raw?JSON.parse(raw):{})}catch(e){bad(e)}})})}
function user(req){const token=(req.headers.cookie||'').match(/mbwp=([^;]+)/)?.[1]; return sessions.get(token);}
function guard(req,res,roles){const u=user(req);if(!u||roles&&!roles.includes(u.role)){json(res,401,{error:'Accès non autorisé'});return null}return u}
function totals(items){let ht=0,tax=0;items.forEach(x=>{ht+=x.priceHt*x.qty;tax+=x.priceHt*x.qty*x.taxRate/100});return {ht:money(ht),tax:money(tax),ttc:money(ht+tax)};}
function dashboard(){const today=new Date().toISOString().slice(0,10);const os=db.orders.filter(o=>o.createdAt.slice(0,10)===today);const revenue=os.filter(o=>o.status!=='CANCELLED').reduce((n,o)=>n+o.total.ttc,0);return {orders:os.length,revenue:money(revenue),average:os.length?money(revenue/os.length):0,activeProducts:db.products.filter(p=>p.active).length,open:db.orders.filter(o=>!['SERVED','CANCELLED'].includes(o.status)).length};}
const server=http.createServer(async(req,res)=>{ const u=new URL(req.url,`http://${req.headers.host}`), p=u.pathname;
  if(p==='/api/health') return json(res,200,{ok:true,time:now()});
  if(p==='/api/login'&&req.method==='POST'){const b=await parse(req);const account=db.users.find(x=>x.email===b.email&&x.password===b.password);if(!account)return json(res,401,{error:'Identifiants invalides'});const token=id();sessions.set(token,{id:account.id,name:account.name,email:account.email,role:account.role});res.writeHead(200,{'Set-Cookie':`mbwp=${token}; HttpOnly; SameSite=Lax; Path=/`,'Content-Type':'application/json'});return res.end(JSON.stringify({user:sessions.get(token)}));}
  if(p==='/api/logout'){const t=(req.headers.cookie||'').match(/mbwp=([^;]+)/)?.[1];sessions.delete(t);res.writeHead(204,{'Set-Cookie':'mbwp=; Max-Age=0; Path=/'});return res.end();}
  if(p==='/api/me'){const x=user(req);return x?json(res,200,x):json(res,401,{error:'Non connecté'});}
  if(p==='/api/events'){const x=guard(req,res);if(!x)return;res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': connected\n\n');streams.add(res);req.on('close',()=>streams.delete(res));return;}
  if(p==='/api/public/catalog') return json(res,200,{venue:db.venue,payment:{cicEnabled:cicReady(),stripeEnabled:stripeReady()},categories:db.categories.filter(c=>c.active),products:db.products.filter(x=>x.active).map(x=>({...x,priceTtc:money(x.priceHt*(1+x.taxRate/100))})),lanes:db.lanes.filter(l=>l.active)});
  if(p==='/api/print/jobs'&&req.method==='GET'){if(!printAgent(req))return json(res,401,{error:'Agent d’impression non autorisé'});return json(res,200,{venue:db.venue,jobs:db.orders.filter(o=>o.status==='NEW'&&o.printStatus!=='PRINTED').slice(-20).reverse()});}
  if(p.match(/^\/api\/print\/jobs\/[^/]+\/ack$/)&&req.method==='POST'){if(!printAgent(req))return json(res,401,{error:'Agent d’impression non autorisé'});const oid=p.split('/')[4],o=db.orders.find(x=>x.id===oid);if(!o)return json(res,404,{error:'Ticket introuvable'});o.printStatus='PRINTED';o.printedAt=now();audit({name:'Agent ticket'},'Ticket imprimé',`#${o.number} · Piste ${o.lane}`);save();return json(res,200,{ok:true});}
  if(p==='/api/public/orders'&&req.method==='POST'){const b=await parse(req), lane=db.lanes.find(l=>l.id===b.laneId),needsPayment=['CIC','STRIPE'].includes(b.paymentMethod);if(b.paymentMethod==='CIC'&&!cicReady())return json(res,503,{error:'Le paiement CIC n’est pas configuré.'});if(b.paymentMethod==='STRIPE'&&!stripeReady())return json(res,503,{error:'Le paiement Stripe n’est pas encore configuré.'});if(!lane)return json(res,400,{error:'Piste invalide'});const items=(b.items||[]).map(x=>{const p=db.products.find(q=>q.id===x.productId&&q.active);return p&&x.qty>0?{productId:p.id,name:p.name,sku:p.sku,priceHt:p.priceHt,taxRate:p.taxRate,qty:+x.qty}:null}).filter(Boolean);if(!items.length)return json(res,400,{error:'Panier vide'});const lacking=items.find(x=>(db.products.find(p=>p.id===x.productId).stock)<x.qty);if(lacking)return json(res,400,{error:`Stock insuffisant : ${lacking.name}`});items.forEach(x=>db.products.find(p=>p.id===x.productId).stock-=x.qty);const o={id:id(),number:1000+db.orders.length+1,laneId:lane.id,lane:lane.number,items,total:totals(items),status:needsPayment?'AWAITING_PAYMENT':'NEW',printStatus:'PENDING',payment:needsPayment?{provider:b.paymentMethod==='STRIPE'?'Stripe':'CIC',status:'PENDING'}:null,createdAt:now(),note:String(b.note||'').slice(0,300)};db.orders.unshift(o);audit(null,'Commande créée',`#${o.number} · Piste ${lane.number} · ${o.total.ttc.toFixed(2)} €`);save();event('changed',{kind:'order',order:o});return json(res,201,o);}
  if(p==='/api/public/payments/stripe'&&req.method==='POST'){const b=await parse(req),o=db.orders.find(x=>x.id===b.orderId&&x.status==='AWAITING_PAYMENT'&&x.payment?.provider==='Stripe');if(!o)return json(res,404,{error:'Commande Stripe introuvable'});if(!stripeReady())return json(res,503,{error:'Configuration Stripe manquante'});const params={mode:'payment',success_url:`${stripe.baseUrl}/api/payments/stripe/return?order=${o.id}&result=success`,cancel_url:`${stripe.baseUrl}/api/payments/stripe/return?order=${o.id}&result=cancel`,client_reference_id:o.id,'metadata[order_id]':o.id,'metadata[order_number]':String(o.number)};if(stripe.configuration)params.payment_method_configuration=stripe.configuration;o.items.forEach((i,n)=>{params[`line_items[${n}][price_data][currency]`]='eur';params[`line_items[${n}][price_data][product_data][name]`]=i.name;params[`line_items[${n}][price_data][unit_amount]`]=String(Math.round(i.priceHt*(1+i.taxRate/100)*100));params[`line_items[${n}][quantity]`]=String(i.qty)});try{const session=await stripePost('/v1/checkout/sessions',params);o.payment.sessionId=session.id;save();return json(res,200,{url:session.url})}catch(e){return json(res,502,{error:e.message})}}
  if(p==='/api/payments/stripe/webhook'&&req.method==='POST'){const raw=await rawBody(req);if(!stripeReady()||!verifyStripe(req,raw)){res.writeHead(400);return res.end('Signature Stripe invalide')}let event;try{event=JSON.parse(raw)}catch{res.writeHead(400);return res.end('JSON invalide')}if(event.type==='checkout.session.completed'&&event.data?.object?.payment_status==='paid'){const session=event.data.object,o=db.orders.find(x=>x.id===session.metadata?.order_id&&x.status==='AWAITING_PAYMENT');if(o){o.status='NEW';o.payment={provider:'Stripe',status:'PAID',sessionId:session.id,paymentIntent:session.payment_intent,paidAt:now()};audit(null,'Paiement Stripe confirmé',`#${o.number} · ${(session.amount_total/100).toFixed(2)} EUR`);save();event&&streams.forEach(r=>r.write(`event: changed\ndata: ${JSON.stringify({kind:'payment',order:o})}\n\n`))}}else if(['checkout.session.expired','checkout.session.async_payment_failed'].includes(event.type)){const oid=event.data?.object?.metadata?.order_id,o=db.orders.find(x=>x.id===oid&&x.status==='AWAITING_PAYMENT');if(o){o.status='CANCELLED';o.payment={provider:'Stripe',status:'FAILED'};releaseStock(o);save()}}res.writeHead(200);return res.end('ok')}
  if(p==='/api/payments/stripe/return'){const result=u.searchParams.get('result');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(`<main style="font:16px system-ui;max-width:480px;margin:10vh auto;text-align:center"><h1>${result==='success'?'Paiement en cours de confirmation':'Paiement annulé'}</h1><p>${result==='success'?'Votre commande sera transmise au bar après confirmation sécurisée Stripe.':'Aucun débit n’est confirmé.'}</p><a href="/">Retour à MB-WP Pay</a></main>`);}
  if(p==='/api/public/payments/cic'&&req.method==='POST'){const b=await parse(req),o=db.orders.find(x=>x.id===b.orderId&&x.status==='AWAITING_PAYMENT');if(!o)return json(res,404,{error:'Commande de paiement introuvable'});if(!cicReady())return json(res,503,{error:'Configuration CIC manquante'});return json(res,200,{action:cic.mode==='production'?'https://p.monetico-services.com/paiement.cgi':'https://p.monetico-services.com/test/paiement.cgi',fields:cicFields(o)});}
  if(p==='/api/payments/cic/notify'&&req.method==='POST'){const b=await formBody(req),o=db.orders.find(x=>x.id===b['texte-libre']),received=String(b.MAC||'').toLowerCase(),expected=cicReady()?cicMac(b):'';const valid=!!o&&/^[0-9a-f]{40}$/.test(received)&&crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected));if(valid&&['paiement','payetest'].includes(b['code-retour'])){o.status='NEW';o.payment={provider:'CIC',status:'PAID',reference:b.reference,authorization:b.numauto||null,paidAt:now()};audit(null,'Paiement CIC confirmé',`#${o.number} · ${b.montant}`);save();event('changed',{kind:'payment',order:o});res.writeHead(200,{'Content-Type':'text/plain'});return res.end('version=2\ncdr=0\n')}if(valid&&o){o.status='CANCELLED';o.payment={provider:'CIC',status:'FAILED'};releaseStock(o);audit(null,'Paiement CIC refusé ou annulé',`#${o.number}`);save();event('changed',{kind:'payment',order:o})}res.writeHead(valid?200:400,{'Content-Type':'text/plain'});return res.end(valid?'version=2\ncdr=0\n':'version=2\ncdr=1\n');}
  if(p==='/api/payments/cic/return'){const oid=u.searchParams.get('order'),result=u.searchParams.get('result'),o=db.orders.find(x=>x.id===oid);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(`<main style="font:16px system-ui;max-width:480px;margin:10vh auto;text-align:center"><h1>${result==='success'?'Paiement en cours de confirmation':'Paiement interrompu'}</h1><p>${result==='success'?'Votre commande sera transmise au bar après confirmation sécurisée CIC.':'Aucun débit n’est confirmé. Vous pouvez retourner au menu.'}</p><a href="/">Retour à MB-WP Pay</a></main>`);}
  if(p==='/api/admin/bootstrap'){const x=guard(req,res);if(!x)return;return json(res,200,{venue:db.venue,users:db.users.map(({password,...a})=>a),categories:db.categories,products:db.products.map(q=>({...q,priceTtc:money(q.priceHt*(1+q.taxRate/100))})),lanes:db.lanes,orders:db.orders,audit:db.audit,dashboard:dashboard()});}
  if(p==='/api/admin/orders'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER','KITCHEN']);if(!x)return;const b=await parse(req),o=db.orders.find(q=>q.id===b.id);if(!o)return json(res,404,{error:'Commande inconnue'});if(!['NEW','PREPARING','READY','SERVED','CANCELLED'].includes(b.status))return json(res,400,{error:'Statut invalide'});o.status=b.status;audit(x,'Statut commande',`#${o.number} → ${b.status}`);save();event('changed',{kind:'order',order:o});return json(res,200,o);}
  if(p==='/api/admin/products'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req);const required=['sku','name','categoryId'];if(required.some(k=>!b[k]))return json(res,400,{error:'SKU, nom et catégorie requis'});if(db.products.some(q=>q.sku.toLowerCase()===String(b.sku).toLowerCase()))return json(res,400,{error:'SKU déjà utilisé'});const q={id:id(),sku:String(b.sku),name:String(b.name),description:String(b.description||''),image:String(b.image||''),featured:!!b.featured,categoryId:b.categoryId,priceHt:money(b.priceHt),taxRate:+b.taxRate,cost:money(b.cost),stock:+b.stock,active:b.active!==false};db.products.push(q);audit(x,'Produit ajouté',q.name);save();event('changed',{kind:'product'});return json(res,201,q);}
  if(p.match(/^\/api\/admin\/products\/[^/]+$/)&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q=db.products.find(a=>a.id===p.split('/').pop());if(!q)return json(res,404,{error:'Produit inconnu'});Object.assign(q,{...b,priceHt:money(b.priceHt),cost:money(b.cost),stock:+b.stock,taxRate:+b.taxRate});audit(x,'Produit modifié',q.name);save();event('changed',{kind:'product'});return json(res,200,q);}
  if(p==='/api/admin/categories'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q={id:id(),name:String(b.name),icon:String(b.icon||'📦'),parentId:b.parentId||null,sort:+b.sort||db.categories.length+1,active:b.active!==false};db.categories.push(q);audit(x,'Catégorie ajoutée',q.name);save();event('changed',{kind:'category'});return json(res,201,q);}
  if(p==='/api/admin/settings'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN']);if(!x)return;const b=await parse(req);db.venue={...db.venue,name:String(b.name||db.venue.name),currency:'EUR',taxIncluded:!!b.taxIncluded};audit(x,'Paramètres modifiés',db.venue.name);save();event('changed',{kind:'settings'});return json(res,200,db.venue);}
  if(p==='/api/admin/users'&&req.method==='POST'){const x=guard(req,res,['ADMIN']);if(!x)return;const b=await parse(req);if(db.users.some(q=>q.email===b.email))return json(res,400,{error:'Adresse déjà utilisée'});const q={id:id(),name:String(b.name),email:String(b.email),password:String(b.password),role:b.role};db.users.push(q);audit(x,'Utilisateur créé',`${q.name} (${q.role})`);save();return json(res,201,{...q,password:undefined});}
  if(p==='/api/admin/lanes'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q=db.lanes.find(l=>l.id===b.id);if(!q)return json(res,404,{error:'Piste inconnue'});q.active=!!b.active;audit(x,'Piste modifiée',`Piste ${q.number}`);save();event('changed',{kind:'lane'});return json(res,200,q);}
  if(p==='/'||p==='/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
  json(res,404,{error:'Route introuvable'});
});
server.listen(PORT,()=>console.log(`MB-WP Pay V2 running at http://localhost:${PORT}`));
