const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const net = require('net');
// Local convenience only: values in .env remain outside the source code and archive.
const envFile=path.join(__dirname,'.env');
if(fs.existsSync(envFile))fs.readFileSync(envFile,'utf8').split(/\r?\n/).forEach(line=>{const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')});

const PORT = process.env.PORT || 3000;
const DB = path.join(__dirname, 'data.json');
const sessions = new Map();
const streams = new Set();
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const money = n => Math.round(Number(n) * 100) / 100;
const cic = {tpe:process.env.CIC_TPE,company:process.env.CIC_SOCIETE,key:process.env.CIC_KEY,baseUrl:process.env.PUBLIC_BASE_URL,mode:process.env.CIC_MODE||'test'};
const stripe = {secret:process.env.STRIPE_SECRET_KEY,webhook:process.env.STRIPE_WEBHOOK_SECRET,configuration:process.env.STRIPE_PAYMENT_METHOD_CONFIGURATION,baseUrl:process.env.PUBLIC_BASE_URL};
const printAgentToken = process.env.PRINT_AGENT_TOKEN || '';
const cicReady = () => !!(cic.tpe && cic.company && /^[0-9a-f]{40}$/i.test(cic.key||'') && /^https:\/\//.test(cic.baseUrl||''));
const cleanBilling = value => {const b=value&&typeof value==='object'?value:{};return {firstName:String(b.firstName||'').trim().slice(0,80),lastName:String(b.lastName||'').trim().slice(0,80),addressLine1:String(b.addressLine1||'').trim().slice(0,140),city:String(b.city||'').trim().slice(0,80),postalCode:String(b.postalCode||'').trim().slice(0,20),country:String(b.country||'FR').trim().toUpperCase().slice(0,2)}};
const billingValid = b => !!(b.addressLine1&&b.city&&b.postalCode&&/^[A-Z]{2}$/.test(b.country));
const stripeReady = () => !!(stripe.secret && stripe.webhook && /^https?:\/\//.test(stripe.baseUrl||''));
function formBody(req){return new Promise(resolve=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>resolve(Object.fromEntries(new URLSearchParams(raw))));});}
function rawBody(req){return new Promise(resolve=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>resolve(raw));});}
function cicMac(fields){const content=Object.keys(fields).filter(k=>k!=='MAC').sort().map(k=>`${k}=${fields[k]??''}`).join('*');return crypto.createHmac('sha1',Buffer.from(cic.key,'hex')).update(content,'utf8').digest('hex');}
function cicFields(order){const date=new Date(),stamp=[String(date.getDate()).padStart(2,'0'),String(date.getMonth()+1).padStart(2,'0'),date.getFullYear()].join('/')+':'+[date.getHours(),date.getMinutes(),date.getSeconds()].map(n=>String(n).padStart(2,'0')).join(':');const reference=`MBWP${order.number}`;const context=Buffer.from(JSON.stringify({billing:order.billing}),'utf8').toString('base64');const fields={TPE:cic.tpe,contexte_commande:context,date:stamp,lgue:'FR',montant:`${order.total.ttc.toFixed(2)}EUR`,reference,societe:cic.company,'texte-libre':order.id,version:'3.0',url_retour_err:`${cic.baseUrl}/api/payments/cic/return?order=${encodeURIComponent(order.id)}&result=error`,url_retour_ok:`${cic.baseUrl}/api/payments/cic/return?order=${encodeURIComponent(order.id)}&result=success`};return {...fields,MAC:cicMac(fields)};}
function printAgent(req){return !!printAgentToken&&req.headers['x-print-agent-token']===printAgentToken;}
function stripePost(path,params){return new Promise((resolve,reject)=>{const body=new URLSearchParams(params).toString(),r=require('https').request({hostname:'api.stripe.com',path,method:'POST',headers:{Authorization:'Basic '+Buffer.from(`${stripe.secret}:`).toString('base64'),'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(body)}},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{const parsed=JSON.parse(out);res.statusCode>=200&&res.statusCode<300?resolve(parsed):reject(Error(parsed.error?.message||'Erreur Stripe'))}catch{reject(Error('Réponse Stripe invalide'))}})});r.on('error',reject);r.end(body)})}
function stripeGet(apiPath){return new Promise((resolve,reject)=>{const r=require('https').request({hostname:'api.stripe.com',path:apiPath,method:'GET',headers:{Authorization:'Basic '+Buffer.from(`${stripe.secret}:`).toString('base64')}},res=>{let out='';res.on('data',c=>out+=c);res.on('end',()=>{try{const parsed=JSON.parse(out);res.statusCode>=200&&res.statusCode<300?resolve(parsed):reject(Error(parsed.error?.message||'Erreur Stripe'))}catch{reject(Error('Réponse Stripe invalide'))}})});r.on('error',reject);r.end()})}
function verifyStripe(req,raw){const signature=String(req.headers['stripe-signature']||''),timestamp=signature.match(/(?:^|,)t=(\d+)/)?.[1],received=signature.match(/(?:^|,)v1=([a-f0-9]+)/i)?.[1];if(!timestamp||!received||Math.abs(Date.now()/1000-Number(timestamp))>300)return false;const expected=crypto.createHmac('sha256',stripe.webhook).update(`${timestamp}.${raw}`,'utf8').digest('hex');return received.length===expected.length&&crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected));}
function sendRawPrint(host,port,content){return new Promise((resolve,reject)=>{const payload=Buffer.concat([Buffer.from('\x1b\x42\x03\x02','binary'),Buffer.isBuffer(content)?content:Buffer.from(content)]),socket=net.createConnection({host,port},()=>socket.end(payload,resolve));socket.setTimeout(8000,()=>socket.destroy(Error('Délai de connexion à l’imprimante dépassé')));socket.on('error',reject)})}
function escposTicket(venue,o){const line='--------------------------------\n',location=o.locationLabel||`Piste ${o.lane||''}`,firstName=o.customerFirstName||'Non renseigné',large='\x1b\x21\x10',xl='\x1b\x21\x30',normal='\x1b\x21\x00';return Buffer.from('\x1b\x40\x1b\x61\x01'+large+venue.name+'\n'+xl+'COMMANDE\n#'+o.number+'\n'+large+'PRENOM : '+firstName+'\nEMPLACEMENT : '+location+'\nREGLEMENT '+(o.payment?.provider||'CB').toUpperCase()+'\nVALIDE\n'+normal+line+'\x1b\x61\x00'+large+'DETAIL COMMANDE\n'+o.items.map(i=>`${i.qty} x ${i.name}\n`+(i.components?.length?i.components.map(c=>' + '+c.name+'\n').join(''):'' )).join('')+normal+line+xl+'TOTAL\n'+o.total.ttc.toFixed(2)+' EUR\n'+large+(o.note?'NOTE : '+o.note+'\n':'')+normal+'\n'+new Date(o.createdAt).toLocaleString('fr-FR')+'\n\n\n\x1d\x56\x00','utf8')}
function queueLocalPrint(o){const printer=db.venue.printer;if(!printer?.enabled||!net.isIP(printer.host)||['PRINTING','PRINTED'].includes(o.printStatus))return;o.printStatus='PRINTING';save();sendRawPrint(printer.host,printer.port||9100,escposTicket(db.venue,o)).then(()=>{o.printStatus='PRINTED';o.printedAt=now();audit({name:'Imprimante locale'},'Ticket imprimé',`#${o.number}`);save()}).catch(e=>{o.printStatus='PRINT_ERROR';o.printError=String(e.message).slice(0,200);audit({name:'Imprimante locale'},'Erreur impression',`#${o.number} · ${o.printError}`);save()})}

function seed() {
  return { venue:{name:'Madiana Bowling by West Paradise',currency:'EUR',taxIncluded:true},
    users:[{id:'u1',name:'Administrateur',email:'admin@mbwp.demo',password:'Demo2026!',role:'ADMIN'},{id:'u2',name:'Bar / Cuisine',email:'bar@mbwp.demo',password:'Demo2026!',role:'KITCHEN'},{id:'u3',name:'Manager',email:'manager@mbwp.demo',password:'Demo2026!',role:'MANAGER'}],
    categories:[
      {id:'c1',name:'Boissons',icon:'🥤',sort:1,active:true,parentId:null},{id:'c2',name:'Salé & Sucré',icon:'🍔',sort:2,active:true,parentId:null},
      {id:'c3',name:'Cocktails avec alcool',icon:'🍹',sort:1,active:true,parentId:'c1'},{id:'c4',name:'Softs',icon:'🥤',sort:2,active:true,parentId:'c1'},
      {id:'c5',name:'Burgers',icon:'🍔',sort:1,active:true,parentId:'c2'},{id:'c6',name:'Snacks',icon:'🍟',sort:2,active:true,parentId:'c2'}],
    products:[
      {id:'p1',sku:'BUR-CHEESE',name:'Cheeseburger',description:'Steak grillé, cheddar, salade et sauce maison.',categoryId:'c5',priceHt:15,taxRate:20,cost:6.2,stock:42,active:true,featured:true,image:''},
      {id:'p2',sku:'BUR-BACON',name:'Burger Bacon',description:'Steak grillé, bacon croustillant, cheddar et sauce barbecue.',categoryId:'c5',priceHt:16.67,taxRate:20,cost:7.4,stock:28,active:true,featured:true,image:''},
      {id:'p3',sku:'DRK-COCA',name:'Coca-Cola 33 cl',description:'Boisson fraîche servie en bouteille.',categoryId:'c4',priceHt:2.92,taxRate:20,cost:0.65,stock:96,active:true,featured:false,image:''},
      {id:'p4',sku:'DRK-HEIN',name:'Bière locale',description:'Bière fraîche locale, 33 cl.',categoryId:'c4',priceHt:5.83,taxRate:20,cost:1.6,stock:47,active:true,featured:false,image:''},
      {id:'p5',sku:'SNK-FRITES',name:'Frites maison',description:'Pommes de terre fraîches, sauce au choix.',categoryId:'c6',priceHt:4.17,taxRate:20,cost:1.1,stock:55,active:true,featured:false,image:''},
      {id:'p6',sku:'SNK-NACHOS',name:'Nachos fromage',description:'Chips de maïs, fromage fondu et salsa.',categoryId:'c6',priceHt:7.5,taxRate:20,cost:2.85,stock:31,active:true,featured:true,image:''},
      {id:'p7',sku:'CKT-MOJITO',name:'Mojito',description:'Rhum blanc, sucre de canne, citron vert, menthe fraîche et eau gazeuse.',categoryId:'c3',priceHt:8.33,taxRate:20,cost:2.5,stock:38,active:true,featured:true,image:''}],
    lanes:Array.from({length:8},(_,i)=>({id:`l${i+1}`,number:i+1,token:crypto.randomBytes(12).toString('hex'),active:true})),orders:[],audit:[] };
}
const obypayCategories=[
  {id:'oby-hennys',name:"Les Henny's",icon:'🍸',sort:10,active:true,parentId:'c1'},
  {id:'oby-citronnes',name:'Les Citronnés',icon:'🍋',sort:11,active:true,parentId:'c1'},
  {id:'oby-renverses',name:'Les Renversés',icon:'🍹',sort:12,active:true,parentId:'c1'},
  {id:'oby-iconiques',name:'Les Iconiques',icon:'⭐',sort:13,active:true,parentId:'c1'},
  {id:'oby-lavish',name:'Lavish',icon:'🥂',sort:14,active:true,parentId:'c1'}
];
const obypayProducts=[
  ['OBY-APPLE-HENNESSY','Apple Hennessy',"Cocktail à base de liqueur de pomme et d'Hennessy",15,'oby-hennys','YnLCSP4dES-1780102825.8119.jpg'],
  ['OBY-APPLE-HENNESSY-ROYAL','Apple Hennessy Royal',"Cocktail à base de liqueur de pomme et d'Hennessy + Champagne",17,'oby-hennys','STDp4Qxmzq-1780103088.3186.jpg'],
  ['OBY-HENNESSY-AMARETTO','Hennessy Amaretto',"Cocktail à base d'Amaretto et de Hennessy",15,'oby-hennys','3TwuvZS9bK-1780103116.2611.jpg'],
  ['OBY-HENNESSY-AMARETTO-ROYAL','Hennessy Amaretto Royal',"Cocktail à base d'Amaretto et de Hennessy + Champagne",17,'oby-hennys','Dkyh91tKsS-1780103161.9434.jpg'],
  ['OBY-HENNESSY-MULE','Hennesy Mule',"Cocktail à base d'Hennessy et de Ginger Beer",14,'oby-hennys','N8U6z8fipm-1780104022.7586.jpg'],
  ['OBY-HENNESSY-VERRE','Hennessy Le Verre','',10,'oby-hennys',''],
  ['OBY-MOJITO','Mojito','',10,'oby-citronnes','BjuG1bXqnR-1780103213.2901.jpg'],
  ['OBY-MOJITO-SIROP','Mojito Sirop','',10,'oby-citronnes','82MWYQB583-1780103270.3533.jpg'],
  ['OBY-MOJITO-ROYAL','Mojito Royal','',16,'oby-citronnes','Hx8SoCVXPe-1780103385.3602.jpg'],
  ['OBY-CAIPIRINIA','Caïpirinia','',10,'oby-citronnes','NBgsZududD-1780103423.8755.jpg'],
  ['OBY-CAIPIRINIA-SIROP','Caïpirinia Sirop','',10,'oby-citronnes','DKBFq3DgZ3-1780103460.7651.jpg'],
  ['OBY-CAIPIRINIA-ROYAL','Caïpirinia Royal','',16,'oby-citronnes','KTa9s63Gsf-1780103493.8611.jpg'],
  ['OBY-DESPERITO','Despérito',"Mojito accompagné d'une Desperados",14,'oby-renverses','fsof2qvo7e-1780103521.5965.jpg'],
  ['OBY-DESPERINIA','Despérinia',"Caïpirinia accompagné d'une Desperados",14,'oby-renverses','HGGaHJSvhS-1780103550.1404.jpg'],
  ['OBY-MAI-TAI','Maï-Taï','Rhum blanc, Rhum vieux, Triple sec, Citron, Orgeat',14,'oby-iconiques','YwqTCUesD2-1780103575.4234.jpg'],
  ['OBY-FLAMANT-ROSE','Flamant Rose','Purée de fraise, Triple sec, Champagne',13,'oby-iconiques','EVcT5xn1rp-1780103609.8761.jpg'],
  ['OBY-PINACOLADA','Pinacolada','Rhum blanc, Ananas frais, Crème de coco, Lait concentré',13,'oby-iconiques','fXBqt1Fawo-1780103649.3126.jpg'],
  ['OBY-CARIBEAN-MULE','Caribean Mule','Rhum vieux, Citron, Ginger beer',12,'oby-iconiques','AfSxq9MSzp-1780103721.0663.jpg'],
  ['OBY-MOSCOW-MULE','Moscow Mule','Vodka, Citron, Ginger Beer',12,'oby-iconiques','UzvMfc9SyQ-1780103746.5387.jpg'],
  ['OBY-EVEIL-SAUVAGE','Eveil Sauvage','Rhum vieux infusé à la menthe, Amaretto, Citron, Limonade',15,'oby-iconiques','J1uWjcPLdQ-1780103879.9167.jpg'],
  ['OBY-GREEN-RUSH','Green Rush','Triple sec, Manzanita, Purée de pomme, Citron',14,'oby-iconiques','UqKXSb1rEL-1780103925.5448.jpg'],
  ['OBY-SCREAMING-ORGASM','Screaming Orgasm','Crème de Rhum vieux, Vodka, Amaretto, Sirop de caramel',15,'oby-iconiques','X6EeKkPDmu-1780103839.6654.jpg'],
  ['OBY-SPICE-MAISON','Spice Maison','',4,'oby-iconiques','6qmchsh8hm-1780104525.5515.jpg'],
  ['OBY-TI-PUNCH','Ti Punch','',8,'oby-iconiques',''],
  ['OBY-RHUM-VIEUX','Rhum Vieux','',10,'oby-iconiques',''],
  ['OBY-FIREBALL','FireBall','',6,'oby-iconiques',''],
  ['OBY-COCKTAIL-SEMAINE','Cocktail de la semaine','',14,'oby-iconiques',''],
  ['OBY-LAVISH-COSMOPOLITAIN','Lavish Cosmopolitain 25cl','',6,'oby-lavish','DSvsUD99I5-1785890527.4445.jpg'],
  ['OBY-LAVISH-MANGOTINI','Lavish Mangotini 25cl','',6,'oby-lavish','GunviBm65N-1785890574.1094.jpg'],
  ['OBY-LAVISH-GIN-FIZZ','Lavish Gin Fizz 25cl','',6,'oby-lavish','dXijIDP9Gq-1785890693.0729.jpg'],
  ['OBY-LAVISH-PURPLE-GRAPE','Lavish Purple Grape 25cl','',6,'oby-lavish','S1wdFA4BPU-1785890640.0717.jpg']
];
function mergeObypayCatalog(d){
  let changed=false;
  obypayCategories.forEach(c=>{if(!d.categories.some(x=>x.id===c.id||x.name.toLowerCase()===c.name.toLowerCase())){d.categories.push(c);changed=true}});
  obypayProducts.forEach(([sku,name,description,priceTtc,categoryId,imageFile])=>{
    const image=imageFile?`/images/products/${path.parse(imageFile).name}.png`:'/images/products/wine-product.webp';
    const values={sku,name,description,categoryId,priceHt:money(priceTtc/1.085),taxRate:8.5,image,active:true,source:'OBYPAY'};
    const existing=d.products.find(x=>x.sku===sku||x.name.toLowerCase()===name.toLowerCase());
    if(existing){if(existing.source!=='OBYPAY'){Object.assign(existing,values);changed=true}else if(/^https?:\/\//.test(existing.image||'')){existing.image=image;changed=true}existing.componentProductIds=existing.componentProductIds||[];existing.upsellProductIds=existing.upsellProductIds||[]}
    else d.products.push({id:`oby-${sku.slice(4).toLowerCase()}`,...values,cost:0,stock:100,featured:false,componentProductIds:[],upsellProductIds:[]});
    if(!existing)changed=true;
  });
  return changed;
}
const requiredMenuCategories=[
  {id:'c3',name:'Cocktails',icon:'🍹',sort:1,parentId:'c1'},
  {id:'menu-mocktails',name:'Cocktails sans alcool',icon:'🍸',sort:2,parentId:'c1'},
  {id:'c4',name:'Soft',icon:'🥤',sort:3,parentId:'c1'},
  {id:'menu-smoothies',name:'Smoothie',icon:'🥭',sort:4,parentId:'c1'},
  {id:'menu-wines',name:'Vins et Champagnes',icon:'🍷',sort:5,parentId:'c1'},
  {id:'menu-ices',name:'Glaces',icon:'🍨',sort:5,parentId:'c2'},
  {id:'menu-tapas',name:'Tapas',icon:'🍤',sort:6,parentId:'c2'}
];
function mergeRequiredCategories(d){let changed=false;requiredMenuCategories.forEach(c=>{let existing=d.categories.find(x=>x.id===c.id);if(existing){if(existing.name!==c.name){existing.name=c.name;changed=true}}else if(!d.categories.some(x=>x.parentId===c.parentId&&x.name.toLowerCase()===c.name.toLowerCase())){d.categories.push({...c,active:true});changed=true}});return changed}
function mergeDefaultOptions(d){let changed=false;if(!Array.isArray(d.optionSets)){d.optionSets=[];changed=true}if(!d.optionSets.some(s=>s.id==='set-desperados')){d.optionSets.push({id:'set-desperados',name:'Choix Desperados',groups:[{id:'desperados',name:'Choix de la Desperados',required:true,choices:[{id:'original',name:'Desperados Original',priceTtcDelta:0},{id:'red',name:'Desperados Red',priceTtcDelta:0},{id:'mojito',name:'Desperados Mojito',priceTtcDelta:0}]}]});changed=true}if(!d.optionSets.some(s=>s.id==='set-sirops')){d.optionSets.push({id:'set-sirops',name:'Choix du sirop',groups:[{id:'sirop',name:'Parfum du sirop',required:true,choices:[{id:'fraise',name:'Fraise',priceTtcDelta:0},{id:'passion',name:'Passion',priceTtcDelta:0},{id:'mangue',name:'Mangue',priceTtcDelta:0},{id:'peche',name:'Pêche',priceTtcDelta:0},{id:'grenadine',name:'Grenadine',priceTtcDelta:0},{id:'violette',name:'Violette',priceTtcDelta:0}]}]});changed=true}d.products.forEach(p=>{if(!Array.isArray(p.optionSetIds)){p.optionSetIds=[];changed=true}});['OBY-DESPERITO','OBY-DESPERINIA'].forEach(sku=>{const product=d.products.find(p=>p.sku===sku);if(product&&!product.optionSetIds.includes('set-desperados')){product.optionSetIds.push('set-desperados');product.optionGroups=(product.optionGroups||[]).filter(g=>g.id!=='desperados');changed=true}});['OBY-MOJITO-SIROP','OBY-CAIPIRINIA-SIROP'].forEach(sku=>{const product=d.products.find(p=>p.sku===sku);if(product&&!product.optionSetIds.includes('set-sirops')){product.optionSetIds.push('set-sirops');changed=true}});return changed}
function migrateCanonicalPricesAndPush(d){d.migrations=d.migrations||{};let changed=false;if(!d.migrations.obypayTtcCanonical){obypayProducts.forEach(([sku,, ,priceTtc])=>{const product=d.products.find(p=>p.sku===sku);if(product){product.priceTtc=money(priceTtc);product.priceHt=money(priceTtc/(1+(product.taxRate||0)/100))}});d.migrations.obypayTtcCanonical=true;changed=true}if(!d.migrations.defaultCocktailPush){const targets=d.products.filter(p=>['SNK-NACHOS','SNK-FRITES'].includes(p.sku)).map(p=>p.id);d.products.filter(p=>p.sku.startsWith('OBY-')).forEach(product=>{product.upsellProductIds=[...new Set([...(product.upsellProductIds||[]),...targets])]});d.migrations.defaultCocktailPush=true;changed=true}return changed}
function load(){const fresh=!fs.existsSync(DB),d=fresh?seed():JSON.parse(fs.readFileSync(DB,'utf8'));let changed=fresh;if(mergeObypayCatalog(d))changed=true;if(mergeRequiredCategories(d))changed=true;if(mergeDefaultOptions(d))changed=true;if(migrateCanonicalPricesAndPush(d))changed=true;d.products.forEach(p=>{if(p.priceTtc===undefined){p.priceTtc=money(p.priceHt*(1+p.taxRate/100));p.priceHt=money(p.priceTtc/(1+p.taxRate/100));changed=true}});d.lanes.forEach(l=>{if(!l.label){l.label=`Piste ${l.number}`;changed=true}});if(!d.venue.printer){d.venue.printer={host:'192.168.1.6',port:9100,enabled:false};changed=true}if(changed)fs.writeFileSync(DB,JSON.stringify(d,null,2));return d;}
let db=load();
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2));}
function audit(user,action,detail){ db.audit.unshift({id:id(),at:now(),user:user?.name||'Client',action,detail}); db.audit=db.audit.slice(0,200);if(['Paiement Stripe confirmé','Paiement CIC confirmé'].includes(action)){const number=Number(String(detail).match(/#(\d+)/)?.[1]),order=db.orders.find(o=>o.number===number);if(order)setImmediate(()=>queueLocalPrint(order))} }
function event(type,payload){ for(const r of streams) r.write(`event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`); }
function releaseStock(order){if(order.stockReleased)return;(order.stockConsumptions||order.items).forEach(i=>{const p=db.products.find(x=>x.id===i.productId);if(p)p.stock+=i.qty});order.stockReleased=true;}
function productComponents(p){return (p.componentProductIds||[]).map(pid=>db.products.find(x=>x.id===pid)).filter(Boolean)}
function saleStock(p){const components=productComponents(p);return components.length?Math.min(...components.map(x=>x.stock)):p.stock}
function cleanOptionGroups(value){return (Array.isArray(value)?value:[]).slice(0,12).map((g,gi)=>({id:String(g.id||`group-${gi+1}`).replace(/[^A-Za-z0-9_-]/g,'').slice(0,40),name:String(g.name||'Option').trim().slice(0,80),required:g.required!==false,choices:(Array.isArray(g.choices)?g.choices:[]).slice(0,20).map((c,ci)=>({id:String(c.id||`choice-${ci+1}`).replace(/[^A-Za-z0-9_-]/g,'').slice(0,40),name:String(c.name||'Choix').trim().slice(0,80),priceTtcDelta:money(c.priceTtcDelta||0)})).filter(c=>c.name)})).filter(g=>g.name&&g.choices.length)}
function productOptionGroups(product){const shared=(product.optionSetIds||[]).flatMap(setId=>db.optionSets?.find(s=>s.id===setId)?.groups||[]);return cleanOptionGroups([...(product.optionGroups||[]),...shared])}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function parse(req){return new Promise((ok,bad)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{ok(raw?JSON.parse(raw):{})}catch(e){bad(e)}})})}
function user(req){const token=(req.headers.cookie||'').match(/mbwp=([^;]+)/)?.[1]; return sessions.get(token);}
function guard(req,res,roles){const u=user(req);if(!u||roles&&!roles.includes(u.role)){json(res,401,{error:'Accès non autorisé'});return null}return u}
function totals(items){let ttc=0,ht=0;items.forEach(x=>{const unitTtc=money(x.priceTtc??x.priceHt*(1+x.taxRate/100));ttc+=unitTtc*x.qty;ht+=unitTtc/(1+x.taxRate/100)*x.qty});ttc=money(ttc);ht=money(ht);return {ht,tax:money(ttc-ht),ttc};}
function dashboard(){const today=new Date().toISOString().slice(0,10);const os=db.orders.filter(o=>o.createdAt.slice(0,10)===today);const revenue=os.filter(o=>o.status!=='CANCELLED').reduce((n,o)=>n+o.total.ttc,0);return {orders:os.length,revenue:money(revenue),average:os.length?money(revenue/os.length):0,activeProducts:db.products.filter(p=>p.active).length,open:db.orders.filter(o=>!['SERVED','CANCELLED'].includes(o.status)).length};}
const server=http.createServer(async(req,res)=>{ const u=new URL(req.url,`http://${req.headers.host}`), p=u.pathname;
  if(p==='/api/health') return json(res,200,{ok:true,time:now()});
  if(p==='/api/login'&&req.method==='POST'){const b=await parse(req);const account=db.users.find(x=>x.email===b.email&&x.password===b.password);if(!account)return json(res,401,{error:'Identifiants invalides'});const token=id();sessions.set(token,{id:account.id,name:account.name,email:account.email,role:account.role});res.writeHead(200,{'Set-Cookie':`mbwp=${token}; HttpOnly; SameSite=Lax; Path=/`,'Content-Type':'application/json'});return res.end(JSON.stringify({user:sessions.get(token)}));}
  if(p==='/api/logout'){const t=(req.headers.cookie||'').match(/mbwp=([^;]+)/)?.[1];sessions.delete(t);res.writeHead(204,{'Set-Cookie':'mbwp=; Max-Age=0; Path=/'});return res.end();}
  if(p==='/api/me'){const x=user(req);return x?json(res,200,x):json(res,401,{error:'Non connecté'});}
  if(p==='/api/events'){const x=guard(req,res);if(!x)return;res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': connected\n\n');streams.add(res);req.on('close',()=>streams.delete(res));return;}
  if(p==='/api/public/catalog') return json(res,200,{venue:db.venue,payment:{cicEnabled:cicReady(),stripeEnabled:stripeReady()},categories:db.categories.filter(c=>c.active),products:db.products.filter(x=>x.active).map(x=>({...x,optionGroups:productOptionGroups(x),stock:saleStock(x),priceTtc:money(x.priceTtc??x.priceHt*(1+x.taxRate/100))})),lanes:db.lanes.filter(l=>l.active)});
  if(p==='/api/print/jobs'&&req.method==='GET'){if(!printAgent(req))return json(res,401,{error:'Agent d’impression non autorisé'});return json(res,200,{venue:db.venue,jobs:db.orders.filter(o=>o.status==='NEW'&&o.payment?.status==='PAID'&&o.printStatus!=='PRINTED').reverse().slice(0,20)});}
  if(p.match(/^\/api\/print\/jobs\/[^/]+\/ack$/)&&req.method==='POST'){if(!printAgent(req))return json(res,401,{error:'Agent d’impression non autorisé'});const oid=p.split('/')[4],o=db.orders.find(x=>x.id===oid);if(!o)return json(res,404,{error:'Ticket introuvable'});o.printStatus='PRINTED';o.printedAt=now();audit({name:'Agent ticket'},'Ticket imprimé',`#${o.number} · Piste ${o.lane}`);save();return json(res,200,{ok:true});}
  if(p==='/api/public/orders'&&req.method==='POST'){
    const b=await parse(req),lane=db.lanes.find(l=>l.id===b.laneId),needsPayment=['CIC','STRIPE'].includes(b.paymentMethod),billing=cleanBilling(b.billing),customerFirstName=String(b.customerFirstName||'').trim().slice(0,50);
    if(b.paymentMethod==='CIC'&&!cicReady())return json(res,503,{error:'Le paiement CIC n’est pas configuré.'});
    if(b.paymentMethod==='CIC'&&!billingValid(billing))return json(res,400,{error:'Adresse de facturation incomplète.'});
    if(b.paymentMethod==='STRIPE'&&!stripeReady())return json(res,503,{error:'Le paiement Stripe n’est pas encore configuré.'});
    if(b.paymentMethod==='STRIPE'&&!customerFirstName)return json(res,400,{error:'Le prénom de la commande est obligatoire.'});
    if(!lane)return json(res,400,{error:'Emplacement invalide'});
    const items=[];
    for(const x of b.items||[]){
      const product=db.products.find(q=>q.id===x.productId&&q.active);if(!product||!(+x.qty>0))continue;
      const submitted=Array.isArray(x.options)?x.options:[],selectedOptions=[];
      for(const group of productOptionGroups(product)){const picked=submitted.find(s=>s.groupId===group.id),choice=group.choices.find(c=>c.id===picked?.choiceId);if(group.required&&!choice)return json(res,400,{error:`Choisissez : ${group.name}`});if(choice)selectedOptions.push({groupId:group.id,groupName:group.name,choiceId:choice.id,choiceName:choice.name,priceTtcDelta:choice.priceTtcDelta})}
      const priceTtc=money((product.priceTtc??product.priceHt*(1+product.taxRate/100))+selectedOptions.reduce((s,o)=>s+o.priceTtcDelta,0)),components=productComponents(product);
      items.push({productId:product.id,name:product.name+(selectedOptions.length?' · '+selectedOptions.map(o=>o.choiceName).join(' / '):''),baseName:product.name,sku:product.sku,priceTtc,priceHt:money(priceTtc/(1+product.taxRate/100)),taxRate:product.taxRate,qty:+x.qty,options:selectedOptions,components:components.map(c=>({productId:c.id,name:c.name}))});
    }
    if(!items.length)return json(res,400,{error:'Panier vide'});
    const consumption=new Map();items.forEach(i=>{const ids=i.components.length?i.components.map(c=>c.productId):[i.productId];ids.forEach(pid=>consumption.set(pid,(consumption.get(pid)||0)+i.qty))});
    const stockConsumptions=[...consumption].map(([productId,qty])=>({productId,qty})),lacking=stockConsumptions.find(x=>(db.products.find(p=>p.id===x.productId)?.stock||0)<x.qty);if(lacking)return json(res,400,{error:`Stock insuffisant : ${db.products.find(p=>p.id===lacking.productId)?.name||'produit'}`});
    stockConsumptions.forEach(x=>db.products.find(p=>p.id===x.productId).stock-=x.qty);
    const locationLabel=String(lane.label||`Piste ${lane.number}`).slice(0,80),o={id:id(),number:1000+db.orders.length+1,laneId:lane.id,lane:lane.number,locationLabel,customerFirstName,items,stockConsumptions,total:totals(items),status:needsPayment?'AWAITING_PAYMENT':'NEW',printStatus:'PENDING',payment:needsPayment?{provider:b.paymentMethod==='STRIPE'?'Stripe':'CIC',status:'PENDING'}:null,createdAt:now(),note:String(b.note||'').slice(0,300),billing:b.paymentMethod==='CIC'?billing:null};
    db.orders.unshift(o);audit(null,'Commande créée',`#${o.number} · ${locationLabel} · ${o.total.ttc.toFixed(2)} €`);save();event('changed',{kind:'order',order:o});return json(res,201,o);
  }
  if(p==='/api/public/payments/stripe'&&req.method==='POST'){const b=await parse(req),o=db.orders.find(x=>x.id===b.orderId&&x.status==='AWAITING_PAYMENT'&&x.payment?.provider==='Stripe');if(!o)return json(res,404,{error:'Commande Stripe introuvable'});if(!stripeReady())return json(res,503,{error:'Configuration Stripe manquante'});const params={mode:'payment',success_url:`${stripe.baseUrl}/api/payments/stripe/return?order=${o.id}&result=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${stripe.baseUrl}/api/payments/stripe/return?order=${o.id}&result=cancel`,client_reference_id:o.id,'metadata[order_id]':o.id,'metadata[order_number]':String(o.number)};if(stripe.configuration)params.payment_method_configuration=stripe.configuration;o.items.forEach((i,n)=>{params[`line_items[${n}][price_data][currency]`]='eur';params[`line_items[${n}][price_data][product_data][name]`]=i.name;params[`line_items[${n}][price_data][unit_amount]`]=String(Math.round(i.priceHt*(1+i.taxRate/100)*100));params[`line_items[${n}][quantity]`]=String(i.qty)});try{const session=await stripePost('/v1/checkout/sessions',params);o.payment.sessionId=session.id;save();return json(res,200,{url:session.url})}catch(e){return json(res,502,{error:e.message})}}
  if(p==='/api/payments/stripe/webhook'&&req.method==='POST'){const raw=await rawBody(req);if(!stripeReady()||!verifyStripe(req,raw)){res.writeHead(400);return res.end('Signature Stripe invalide')}let event;try{event=JSON.parse(raw)}catch{res.writeHead(400);return res.end('JSON invalide')}if(event.type==='checkout.session.completed'&&event.data?.object?.payment_status==='paid'){const session=event.data.object,o=db.orders.find(x=>x.id===session.metadata?.order_id&&x.status==='AWAITING_PAYMENT');if(o){o.status='NEW';o.payment={provider:'Stripe',status:'PAID',sessionId:session.id,paymentIntent:session.payment_intent,paidAt:now()};audit(null,'Paiement Stripe confirmé',`#${o.number} · ${(session.amount_total/100).toFixed(2)} EUR`);save();event&&streams.forEach(r=>r.write(`event: changed\ndata: ${JSON.stringify({kind:'payment',order:o})}\n\n`))}}else if(['checkout.session.expired','checkout.session.async_payment_failed'].includes(event.type)){const oid=event.data?.object?.metadata?.order_id,o=db.orders.find(x=>x.id===oid&&x.status==='AWAITING_PAYMENT');if(o){o.status='CANCELLED';o.payment={provider:'Stripe',status:'FAILED'};releaseStock(o);save()}}res.writeHead(200);return res.end('ok')}
  if(p==='/api/payments/stripe/return'){const result=u.searchParams.get('result'),sessionId=u.searchParams.get('session_id'),orderId=u.searchParams.get('order'),o=db.orders.find(x=>x.id===orderId);let paid=o?.payment?.status==='PAID';if(result==='success'&&sessionId&&o&&!paid){try{const session=await stripeGet(`/v1/checkout/sessions/${encodeURIComponent(sessionId)}`);if(session.payment_status==='paid'&&session.metadata?.order_id===o.id){o.status='NEW';o.payment={provider:'Stripe',status:'PAID',sessionId:session.id,paymentIntent:session.payment_intent,paidAt:now()};audit(null,'Paiement Stripe confirmé',`#${o.number} · ${(session.amount_total/100).toFixed(2)} EUR`);save();event('changed',{kind:'payment',order:o});paid=true}}catch(e){console.error('Confirmation retour Stripe:',e.message)}}const lane=db.lanes.find(l=>l.id===o?.laneId),target=lane?`/?location=${encodeURIComponent(lane.id)}&token=${encodeURIComponent(lane.token)}`:'/',title=paid?'Paiement confirmé':result==='cancel'?'Paiement annulé':'Paiement en cours de confirmation',message=paid?'Votre règlement est validé. La commande a été transmise et envoyée à l’impression.':result==='cancel'?'Aucun débit n’est confirmé. Votre panier a été conservé.':'La confirmation Stripe n’est pas encore arrivée.';res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(`<main style="font:16px system-ui;max-width:520px;margin:10vh auto;text-align:center"><h1>${title}</h1><p>${message}</p><p>Retour au menu dans <b id="count">3</b> secondes…</p><a href="${target}">Retour immédiat</a></main><script>${paid?"localStorage.removeItem('mbwp-cart');localStorage.removeItem('mbwp-cart-updated');":''}let n=3;setInterval(()=>{n--;document.getElementById('count').textContent=Math.max(0,n);if(n<=0)location.replace(${JSON.stringify(target)})},1000)</script>`);}
  if(p==='/api/public/payments/cic'&&req.method==='POST'){const b=await parse(req),o=db.orders.find(x=>x.id===b.orderId&&x.status==='AWAITING_PAYMENT');if(!o)return json(res,404,{error:'Commande de paiement introuvable'});if(!cicReady())return json(res,503,{error:'Configuration CIC manquante'});return json(res,200,{action:cic.mode==='production'?'https://p.monetico-services.com/paiement.cgi':'https://p.monetico-services.com/test/paiement.cgi',fields:cicFields(o)});}
  if(p==='/api/payments/cic/notify'&&req.method==='POST'){const b=await formBody(req),o=db.orders.find(x=>x.id===b['texte-libre']),received=String(b.MAC||'').toLowerCase(),expected=cicReady()?cicMac(b):'';const valid=!!o&&/^[0-9a-f]{40}$/.test(received)&&crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected));if(valid&&['paiement','payetest'].includes(b['code-retour'])){o.status='NEW';o.payment={provider:'CIC',status:'PAID',reference:b.reference,authorization:b.numauto||null,paidAt:now()};audit(null,'Paiement CIC confirmé',`#${o.number} · ${b.montant}`);save();event('changed',{kind:'payment',order:o});res.writeHead(200,{'Content-Type':'text/plain'});return res.end('version=2\ncdr=0\n')}if(valid&&o){o.status='CANCELLED';o.payment={provider:'CIC',status:'FAILED'};releaseStock(o);audit(null,'Paiement CIC refusé ou annulé',`#${o.number}`);save();event('changed',{kind:'payment',order:o})}res.writeHead(valid?200:400,{'Content-Type':'text/plain'});return res.end(valid?'version=2\ncdr=0\n':'version=2\ncdr=1\n');}
  if(p==='/api/payments/cic/return'){const oid=u.searchParams.get('order'),result=u.searchParams.get('result'),o=db.orders.find(x=>x.id===oid);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(`<main style="font:16px system-ui;max-width:480px;margin:10vh auto;text-align:center"><h1>${result==='success'?'Paiement en cours de confirmation':'Paiement interrompu'}</h1><p>${result==='success'?'Votre commande sera transmise au bar après confirmation sécurisée CIC.':'Aucun débit n’est confirmé. Vous pouvez retourner au menu.'}</p><a href="/">Retour à MB-WP Pay</a></main>`);}
  if(p==='/api/admin/bootstrap'){const x=guard(req,res);if(!x)return;return json(res,200,{venue:db.venue,payment:{stripeEnabled:stripeReady(),stripeMode:String(stripe.secret||'').includes('_test_')?'test':'production',stripeWebhookConfigured:!!stripe.webhook,stripePaymentConfiguration:!!stripe.configuration,cicEnabled:cicReady()},users:db.users.map(({password,...a})=>a),categories:db.categories,optionSets:db.optionSets||[],products:db.products.map(q=>({...q,priceTtc:money(q.priceTtc??q.priceHt*(1+q.taxRate/100))})),lanes:db.lanes,orders:db.orders,audit:db.audit,dashboard:dashboard()});}
  if(p==='/api/admin/images'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'},ext=types[String(b.type||'')],match=String(b.data||'').match(/^data:image\/(?:jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!ext||!match)return json(res,400,{error:'Format accepté : JPG, PNG ou WebP'});let content;try{content=Buffer.from(match[1],'base64')}catch{return json(res,400,{error:'Fichier image invalide'})}if(!content.length||content.length>5*1024*1024)return json(res,400,{error:'L’image doit peser moins de 5 Mo'});const dir=path.join(__dirname,'images','products','uploads'),name=`${Date.now()}-${crypto.randomBytes(6).toString('hex')}.${ext}`,file=path.join(dir,name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,content);audit(x,'Image produit ajoutée',name);return json(res,201,{url:`/images/products/uploads/${name}`});}
  if(p==='/api/admin/orders'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER','KITCHEN']);if(!x)return;const b=await parse(req),o=db.orders.find(q=>q.id===b.id);if(!o)return json(res,404,{error:'Commande inconnue'});if(!['NEW','PREPARING','READY','SERVED','CANCELLED'].includes(b.status))return json(res,400,{error:'Statut invalide'});o.status=b.status;audit(x,'Statut commande',`#${o.number} → ${b.status}`);save();event('changed',{kind:'order',order:o});return json(res,200,o);}
  if(p==='/api/admin/products'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req);const required=['sku','name','categoryId'];if(required.some(k=>!b[k]))return json(res,400,{error:'SKU, nom et catégorie requis'});if(db.products.some(q=>q.sku.toLowerCase()===String(b.sku).toLowerCase()))return json(res,400,{error:'SKU déjà utilisé'});const taxRate=+b.taxRate||0,priceTtc=money(b.priceTtc),cleanIds=v=>[...new Set((Array.isArray(v)?v:[]).map(String))].filter(pid=>db.products.some(p=>p.id===pid)),q={id:id(),sku:String(b.sku),name:String(b.name),description:String(b.description||''),image:String(b.image||''),featured:!!b.featured,categoryId:b.categoryId,priceTtc,priceHt:money(priceTtc/(1+taxRate/100)),taxRate,cost:money(b.cost),stock:+b.stock,active:b.active!==false,componentProductIds:cleanIds(b.componentProductIds),upsellProductIds:cleanIds(b.upsellProductIds),optionGroups:cleanOptionGroups(b.optionGroups)};db.products.push(q);audit(x,'Produit ajouté',q.name);save();event('changed',{kind:'product'});return json(res,201,q);}
  if(p.match(/^\/api\/admin\/products\/[^/]+$/)&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q=db.products.find(a=>a.id===p.split('/').pop());if(!q)return json(res,404,{error:'Produit inconnu'});const sku=String(b.sku||'').trim(),name=String(b.name||'').trim();if(!sku||!name||!b.categoryId)return json(res,400,{error:'SKU, nom et catégorie requis'});if(db.products.some(a=>a.id!==q.id&&a.sku.toLowerCase()===sku.toLowerCase()))return json(res,400,{error:'SKU déjà utilisé'});const taxRate=+b.taxRate||0,priceTtc=money(b.priceTtc),cleanIds=v=>[...new Set((Array.isArray(v)?v:[]).map(String))].filter(pid=>pid!==q.id&&db.products.some(p=>p.id===pid));Object.assign(q,{sku,name,description:String(b.description||''),image:String(b.image||''),categoryId:String(b.categoryId),priceTtc,priceHt:money(priceTtc/(1+taxRate/100)),cost:money(b.cost),stock:Math.max(0,Math.floor(Number(b.stock)||0)),taxRate,active:b.active!==false,featured:!!b.featured,componentProductIds:cleanIds(b.componentProductIds),upsellProductIds:cleanIds(b.upsellProductIds),optionGroups:cleanOptionGroups(b.optionGroups)});audit(x,'Produit modifié',q.name);save();event('changed',{kind:'product'});return json(res,200,q);}
  if(p.match(/^\/api\/admin\/products\/[^/]+$/)&&req.method==='DELETE'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const productId=p.split('/').pop(),index=db.products.findIndex(product=>product.id===productId);if(index<0)return json(res,404,{error:'Produit inconnu'});const [removed]=db.products.splice(index,1);db.products.forEach(product=>{product.componentProductIds=(product.componentProductIds||[]).filter(id=>id!==productId);product.upsellProductIds=(product.upsellProductIds||[]).filter(id=>id!==productId)});audit(x,'Produit supprimé',`${removed.sku} · ${removed.name}`);save();event('changed',{kind:'product'});return json(res,200,{ok:true});}
  if(p==='/api/admin/option-sets'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),name=String(b.name||'').trim().slice(0,80),groups=cleanOptionGroups(b.groups);if(!name||!groups.length)return json(res,400,{error:'Nom et options requis'});const set={id:id(),name,groups};db.optionSets=db.optionSets||[];db.optionSets.push(set);const productIds=new Set(Array.isArray(b.productIds)?b.productIds:[]);db.products.forEach(product=>{product.optionSetIds=product.optionSetIds||[];if(productIds.has(product.id)&&!product.optionSetIds.includes(set.id))product.optionSetIds.push(set.id)});audit(x,'Jeu d’options créé',name);save();event('changed',{kind:'option-set'});return json(res,201,set);}
  if(p.match(/^\/api\/admin\/option-sets\/[^/]+$/)&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),set=db.optionSets?.find(s=>s.id===p.split('/').pop());if(!set)return json(res,404,{error:'Jeu d’options inconnu'});const name=String(b.name||'').trim().slice(0,80),groups=cleanOptionGroups(b.groups);if(!name||!groups.length)return json(res,400,{error:'Nom et options requis'});set.name=name;set.groups=groups;const productIds=new Set(Array.isArray(b.productIds)?b.productIds:[]);db.products.forEach(product=>{product.optionSetIds=(product.optionSetIds||[]).filter(id=>id!==set.id);if(productIds.has(product.id))product.optionSetIds.push(set.id)});audit(x,'Jeu d’options modifié',name);save();event('changed',{kind:'option-set'});return json(res,200,set);}
  if(p.match(/^\/api\/admin\/option-sets\/[^/]+$/)&&req.method==='DELETE'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const setId=p.split('/').pop(),index=db.optionSets?.findIndex(s=>s.id===setId);if(index===undefined||index<0)return json(res,404,{error:'Jeu d’options inconnu'});const [removed]=db.optionSets.splice(index,1);db.products.forEach(product=>product.optionSetIds=(product.optionSetIds||[]).filter(id=>id!==setId));audit(x,'Jeu d’options supprimé',removed.name);save();event('changed',{kind:'option-set'});return json(res,200,{ok:true});}
  if(p==='/api/admin/categories'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q={id:id(),name:String(b.name),icon:String(b.icon||'📦'),parentId:b.parentId||null,sort:+b.sort||db.categories.length+1,active:b.active!==false};db.categories.push(q);audit(x,'Catégorie ajoutée',q.name);save();event('changed',{kind:'category'});return json(res,201,q);}
  if(p.match(/^\/api\/admin\/categories\/[^/]+$/)&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),category=db.categories.find(c=>c.id===p.split('/').pop());if(!category)return json(res,404,{error:'Catégorie inconnue'});const name=String(b.name||'').trim().slice(0,80);if(!name)return json(res,400,{error:'Nom de catégorie requis'});Object.assign(category,{name,icon:String(b.icon||'📦').slice(0,8),sort:+b.sort||category.sort,active:b.active!==false});if(b.parentId!==undefined&&b.parentId!==category.id)category.parentId=b.parentId||null;const productIds=new Set(Array.isArray(b.productIds)?b.productIds:[]);db.products.forEach(product=>{if(productIds.has(product.id))product.categoryId=category.id});audit(x,'Catégorie modifiée',name);save();event('changed',{kind:'category'});return json(res,200,category);}
  if(p.match(/^\/api\/admin\/categories\/[^/]+$/)&&req.method==='DELETE'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),categoryId=p.split('/').pop(),index=db.categories.findIndex(c=>c.id===categoryId);if(index<0)return json(res,404,{error:'Catégorie inconnue'});if(db.categories.some(c=>c.parentId===categoryId))return json(res,400,{error:'Supprimez ou déplacez d’abord les sous-catégories'});const products=db.products.filter(product=>product.categoryId===categoryId),replacement=db.categories.find(c=>c.id===b.replacementCategoryId&&c.id!==categoryId&&c.parentId);if(products.length&&!replacement)return json(res,400,{error:'Choisissez une catégorie de remplacement pour les produits'});products.forEach(product=>product.categoryId=replacement.id);const [removed]=db.categories.splice(index,1);audit(x,'Catégorie supprimée',removed.name);save();event('changed',{kind:'category'});return json(res,200,{ok:true,movedProducts:products.length});}
  if(p==='/api/admin/settings'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN']);if(!x)return;const b=await parse(req),host=String(b.printerHost||'').trim(),port=Math.floor(Number(b.printerPort)||9100),enabled=!!b.printerEnabled;if(enabled&&!net.isIP(host))return json(res,400,{error:'Adresse IP de l’imprimante invalide'});if(port<1||port>65535)return json(res,400,{error:'Port imprimante invalide'});db.venue={...db.venue,name:String(b.name||db.venue.name),currency:'EUR',taxIncluded:!!b.taxIncluded,printer:{host,port,enabled}};audit(x,'Paramètres modifiés',db.venue.name);save();event('changed',{kind:'settings'});return json(res,200,db.venue);}
  if(p==='/api/admin/printer/test'&&req.method==='POST'){const x=guard(req,res,['ADMIN']);if(!x)return;const printer=db.venue.printer;if(!printer?.host||!net.isIP(printer.host))return json(res,400,{error:'Configurez une adresse IP valide puis enregistrez les paramètres'});const test=Buffer.from('\x1b\x40\x1b\x61\x01\x1b\x21\x10'+db.venue.name+'\n\x1b\x21\x30TEST\nIMPRIMANTE\x1b\x21\x10\nConnexion reussie\nIP : '+printer.host+'\nPort : '+printer.port+'\n\x1b\x21\x00Date : '+new Date().toLocaleString('fr-FR')+'\n\n\n\x1d\x56\x00','utf8');try{await sendRawPrint(printer.host,printer.port,test);audit(x,'Test imprimante réussi',`${printer.host}:${printer.port}`);save();return json(res,200,{ok:true})}catch(e){audit(x,'Échec test imprimante',String(e.message).slice(0,160));save();return json(res,502,{error:`Impossible de joindre l’imprimante : ${e.message}`})}}
  if(p==='/api/admin/users'&&req.method==='POST'){const x=guard(req,res,['ADMIN']);if(!x)return;const b=await parse(req);if(db.users.some(q=>q.email===b.email))return json(res,400,{error:'Adresse déjà utilisée'});const q={id:id(),name:String(b.name),email:String(b.email),password:String(b.password),role:b.role};db.users.push(q);audit(x,'Utilisateur créé',`${q.name} (${q.role})`);save();return json(res,201,{...q,password:undefined});}
  if(p==='/api/admin/lanes'&&req.method==='POST'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),label=String(b.label||'').trim().slice(0,80);if(!label)return json(res,400,{error:'Le nom de l’emplacement est obligatoire'});const next=Math.max(0,...db.lanes.map(l=>Number(l.number)||0))+1,q={id:id(),number:next,label,token:crypto.randomBytes(12).toString('hex'),active:true};db.lanes.push(q);audit(x,'Lien QR créé',label);save();event('changed',{kind:'lane'});return json(res,201,q);}
  if(p==='/api/admin/lanes'&&req.method==='PATCH'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const b=await parse(req),q=db.lanes.find(l=>l.id===b.id);if(!q)return json(res,404,{error:'Emplacement inconnu'});if(b.label!==undefined){const label=String(b.label).trim().slice(0,80);if(!label)return json(res,400,{error:'Le nom est obligatoire'});q.label=label}if(b.active!==undefined)q.active=!!b.active;if(b.regenerateToken)q.token=crypto.randomBytes(12).toString('hex');audit(x,b.regenerateToken?'Lien QR régénéré':'Emplacement modifié',q.label||`Piste ${q.number}`);save();event('changed',{kind:'lane'});return json(res,200,q);}
  if(p.match(/^\/api\/admin\/lanes\/[^/]+$/)&&req.method==='DELETE'){const x=guard(req,res,['ADMIN','MANAGER']);if(!x)return;const laneId=p.split('/').pop(),index=db.lanes.findIndex(l=>l.id===laneId);if(index<0)return json(res,404,{error:'Emplacement inconnu'});const [removed]=db.lanes.splice(index,1);audit(x,'Lien QR supprimé',removed.label||`Piste ${removed.number}`);save();event('changed',{kind:'lane'});return json(res,200,{ok:true});}
  if(/^\/images\/products\/(?:uploads\/)?[A-Za-z0-9._-]+$/.test(p)){const root=path.join(__dirname,'images','products'),file=path.resolve(__dirname,p.slice(1));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return json(res,404,{error:'Image introuvable'});const ext=path.extname(file).toLowerCase(),type=ext==='.webp'?'image/webp':ext==='.png'?'image/png':ext==='.jpg'||ext==='.jpeg'?'image/jpeg':'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':'public, max-age=86400'});return fs.createReadStream(file).pipe(res)}
  if(p==='/'||p==='/index.html'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(__dirname,'index.html')).pipe(res)}
  json(res,404,{error:'Route introuvable'});
});
server.listen(PORT,()=>console.log(`MB-WP Pay V2 running at http://localhost:${PORT}`));
